### ISSUE TITLE
Incompatibility between non-Unicode and Unicode version

### ISSUE THREAD

**Issue by unixguru65** [TurboPack/OnGuard-VCL#1]
The GenerateStringModifierPrim routine in the OnGuard.pas unit seems to have undergone a simple Unicode conversion that unfortunately makes the results different between non-Unicode and Unicode versions of OnGuard.

**Comment by romankassebaum** [comment]
I hope that fixes the issue:

function GenerateStringModifierPrim(const S : string) : Integer;
var
  I     : Integer;                                                       {!!.06}
  Sig   : array [0..3] of Byte;
  S2    : string;                                                        {!!.06}
  Buffer: TBytes;
begin
  FillChar(Sig, SizeOf(Sig), 0);

  {strip accented characters from the string}                          {!!.06}
  S2 := S;                                                             {!!.06}
  for I := S2.Length - 1 downto 0 do                                   {!!.06}
    if Ord(S2.Chars[I]) > 127 then                                     {!!.06}
      S2.Remove(I, 1);                                                 {!!.06}
  Buffer := TEncoding.ANSI.GetBytes(S2);
  Move(Buffer[0], Sig, Min(Length(Sig), Length(Buffer)));
  Result := PInteger(@Sig[0])^;
end;
