### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by stevewe** [TurboPack/OnGuard-VCL#2]
Have you actually used your installation instructions? They don't seem to work. I keep getting hung up on the definition of TCode when I try to compile an app using TogMakeKeys.

**Comment by romankassebaum** [comment]
Yesterday I fixed a bug concerning the TogMakeKeys component (Revision 23). Did you try this revision?

**Comment by stevewe** [comment]
Yes. I did try it as an install to Dephi XE8. It hangs on a compile with a error about TCode. I think there must be more involved with the libraries. Will you be updating Embarcadero's GetIt link?

**Comment by romankassebaum** [comment]
I just cloned the current version from github, not from getit. Then I opened the Delphi project group and built all projects. And it did compile without a single warning or hint.

Can you attach the error messages?

Embarcadero must update the link, I already asked them to do so.
